# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1543e4d5582d8d09a2e618bb9010c9439ce91f08c19c944a1e8ba777506378ef7f4b7a3fbe67f162d51f0021c53e4cf379f1897f32996786ff2f094662113045

test:
  secret_key_base: 728048232a953f38a58d39e84f7b816ed16a8fe91e9086d7563af5d16d859985a8018cb74a4d53b3690776590e66d1f0373c3c25e972470d577d6edc58f179bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
